---
dns_service_state: started
dns_service_enabled: true

dns_services:
  - named

dns_ports:
  - 53

bind_zone_dir: /var/named/dynamic/
bind_zone_file_mode: '0660'
bind_allow_query:
  - any
bind_listen_ipv4:
  - any
bind_listen_ipv6:
  - any
bind_acls:
  - name: acl1
    match_list:
      - 172.17.0.0/16
bind_forwarders:
  - '8.8.8.8'
  - '8.8.4.4'
bind_recursion: true
bind_query_log: 'data/query.log'
bind_check_names: 'master ignore'
bind_zone_master_server_ip: 172.17.0.2
bind_zone_minimum_ttl: "2D"
bind_zone_ttl: "2W"
bind_zone_time_to_refresh: "2D"
bind_zone_time_to_retry: "2H"
bind_zone_time_to_expire: "2W"
bind_zone_domains:
  - name: 'example.com'
    networks:
      - '192.0.2'
    ipv6_networks:
      - '2001:db9::/48'
    name_servers:
      - ns1.acme-inc.com.
      - ns2.acme-inc.com.
    hostmaster_email: admin
    hosts:
      - name: srv001
        ip: 192.0.2.1
        ipv6: '2001:db9::1'
        aliases:
          - www
      - name: srv002
        ip: 192.0.2.2
        ipv6: '2001:db9::2'
      - name: mail001
        ip: 192.0.2.10
        ipv6: '2001:db9::3'
    mail_servers:
      - name: mail001
        preference: 10
    services:
      - name: _ldap._tcp
        weight: 100
        port: 88
        target: srv010
    text:
      - name: _kerberos
        text: KERBEROS.ACME-INC.COM
      - name: '@'
        text:
          - 'some text'
          - 'more text'
...
